name: Create release and upload artifacts

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    name: Build release artifacts, create release and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          # https://github.com/actions/go-versions/blob/main/versions-manifest.json
          go-version: 'stable'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: |
          GOOS=linux   GOARCH=amd64 go build -v ./cmd/certyaml && tar zcvf certyaml-linux-amd64.tar.gz  certyaml && rm certyaml
          GOOS=darwin  GOARCH=amd64 go build -v ./cmd/certyaml && tar zcvf certyaml-darwin-amd64.tar.gz certyaml && rm certyaml
          GOOS=darwin  GOARCH=arm64 go build -v ./cmd/certyaml && tar zcvf certyaml-darwin-arm64.tar.gz certyaml && rm certyaml
          GOOS=windows GOARCH=amd64 go build -v ./cmd/certyaml && zip      certyaml-windows-amd64.zip   certyaml.exe && rm certyaml.exe

      # https://github.com/softprops/action-gh-release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            certyaml-linux-amd64.tar.gz
            certyaml-darwin-amd64.tar.gz
            certyaml-darwin-arm64.tar.gz
            certyaml-windows-amd64.zip
