name: trivy scan
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/aquasecurity/trivy-action
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.16.1
        with:
          scan-type: "fs"
          format: "sarif"
          output: "trivy-results.sarif"
          scanners: "vuln,secret,config"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
