name: unit-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        # https://github.com/actions/go-versions/blob/main/versions-manifest.json
        go-version: 'stable'
      id: go

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
          version: v1.50.1

    - name: Build
      run: make build

    - name: Unit tests
      run: make test
